[GLOBAL]
pants_version = "2.29.0"
pythonpath = ["%(buildroot)s/src/python"]
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.experimental.python.typecheck.pyright",
  "pants.backend.plugin_development",
  "gusi.pants.backend.alembic",
  "gusi.pants.backend.ray",
]
print_stacktrace = true

[python]
enable_resolves = true
enable_lockfile_targets = true
default_resolve = "gusi-pants-plugins"
interpreter_constraints = ["==3.11.*"]

[python.resolves_to_interpreter_constraints]
gusi-pants-plugins = ["==3.11.*"]
test-resolve = [">=3.10,<3.15"]

[cli.alias]
venv = "export --resolve=gusi-pants-plugins"
lock = "generate-lockfiles --resolve=gusi-pants-plugins"

[python.resolves]
gusi-pants-plugins = "3rdparty/python/gusi-pants-plugins.lock"
test-resolve = "3rdparty/python/test.lock"

[system-binaries]
system_binary_paths = ["<PATH>"]
