"""Templates for Ray job submission scripts."""

from typing import Dict, List, Optional


def get_submit_script_template(
    entry_point: str,
    num_cpus: float,
    num_gpus: float,
    memory: int,
    ray_address: str,
    env_vars: Optional[Dict[str, Optional[str]]] = None,
    secrets: Optional[List[str]] = None,
) -> str:
    """Generate the submit.py script content.

    The script reads RAY_JOB_PEX env var (path to the job PEX built by Pants),
    uploads it to the Ray cluster, and submits the job using it as the
    Python environment.

    Args:
        entry_point: Python module entry point (e.g., "ictl.job.supsi.crawl_uspto.main")
        num_cpus: Number of CPU cores to allocate
        num_gpus: Number of GPUs to allocate
        memory: Memory allocation in bytes
        ray_address: Ray cluster address (or "auto")
        env_vars: Dict of env vars (None value = required)
        secrets: List of secret env var names

    Returns:
        Generated Python script content
    """
    env_vars = env_vars or {}
    secrets = secrets or []

    # Separate fixed and required env vars
    fixed_vars = {k: v for k, v in env_vars.items() if v is not None}
    required_vars = [k for k, v in env_vars.items() if v is None]

    # Build the script
    lines = [
        "#!/usr/bin/env python3",
        '"""Auto-generated Ray job submission script.',
        "",
        f"This script submits the {entry_point} job to a Ray cluster.",
        "It uploads a pre-built PEX and runs it on the cluster.",
        "Generated by gusi.pants.backend.ray - DO NOT EDIT MANUALLY.",
        '"""',
        "",
        "import os",
        "import shutil",
        "import sys",
        "import tempfile",
        "",
        "from ray.job_submission import JobSubmissionClient",
        "",
    ]

    # RAY_JOB_PEX is required - set by pants ray-submit goal
    lines.extend([
        '_RAY_JOB_PEX = os.environ.get("RAY_JOB_PEX")',
        'if not _RAY_JOB_PEX:',
        '    print("ERROR: RAY_JOB_PEX env var not set.", file=sys.stderr)',
        '    print("Use: pants ray-submit <ray_job_target>", file=sys.stderr)',
        "    sys.exit(1)",
        "",
        "if not os.path.isfile(_RAY_JOB_PEX):",
        '    print(f"ERROR: RAY_JOB_PEX file not found: {_RAY_JOB_PEX}", file=sys.stderr)',
        "    sys.exit(1)",
        "",
        "# Optional: pinned requirements.txt for cluster-side pip install",
        '_RAY_JOB_REQUIREMENTS = os.environ.get("RAY_JOB_REQUIREMENTS")',
        'if _RAY_JOB_REQUIREMENTS and not os.path.isfile(_RAY_JOB_REQUIREMENTS):',
        '    print(f"ERROR: RAY_JOB_REQUIREMENTS file not found: {_RAY_JOB_REQUIREMENTS}", file=sys.stderr)',
        "    sys.exit(1)",
        "",
    ])

    # Add required env vars check
    if required_vars:
        lines.extend([
            "# Required environment variables - fail fast if missing",
            f"_REQUIRED_ENV_VARS = {required_vars!r}",
            "",
            "def _check_required_env_vars() -> None:",
            '    """Check that all required env vars are set."""',
            "    missing = [k for k in _REQUIRED_ENV_VARS if not os.getenv(k)]",
            "    if missing:",
            "        missing_str = \", \".join(missing)",
            "        print(f\"ERROR: Missing required environment variables: {missing_str}\", file=sys.stderr)",
            "        sys.exit(1)",
            "",
            "_check_required_env_vars()",
            "",
        ])

    # Add fixed env vars
    if fixed_vars:
        lines.extend([
            "# Fixed environment variables (hardcoded)",
            f"_FIXED_ENV_VARS = {fixed_vars!r}",
            "",
        ])

    # Add secrets handling
    if secrets:
        lines.extend([
            "# Secret environment variables (loaded from environment)",
            f"_SECRET_ENV_VARS = {secrets!r}",
            "",
        ])

    # Build the runtime env vars dict
    lines.extend([
        "# Build runtime environment variables",
        "_env_vars = {}",
        "",
    ])

    if fixed_vars:
        lines.extend([
            "_env_vars.update(_FIXED_ENV_VARS)",
            "",
        ])

    if required_vars:
        lines.extend([
            "# Add required env vars from environment",
            "for k in _REQUIRED_ENV_VARS:",
            "    _env_vars[k] = os.environ[k]",
            "",
        ])

    if secrets:
        lines.extend([
            "# Add secrets from environment (optional)",
            "for k in _SECRET_ENV_VARS:",
            "    if os.getenv(k):",
            "        _env_vars[k] = os.environ[k]",
            "",
        ])

    # Build ray address
    if ray_address == "auto":
        lines.extend([
            "# Get Ray address from environment or use auto-detect",
            '_ray_address = os.getenv("RAY_ADDRESS", "auto")',
            "",
        ])
        ray_addr_var = "_ray_address"
    else:
        ray_addr_var = repr(ray_address)

    # Main submission logic
    lines.extend([
        "def submit_job() -> str:",
        '    """Upload job PEX to Ray cluster and submit the job."""',
        f"    client = JobSubmissionClient({ray_addr_var})",
        "",
        "    print(f\"Packaging job PEX for upload: {_RAY_JOB_PEX}\")",
        "    _tmpdir = tempfile.mkdtemp()",
        '    _pex_in_working_dir = os.path.join(_tmpdir, "job.pex")',
        '    shutil.copy2(_RAY_JOB_PEX, _pex_in_working_dir)',
        "",
        '    _runtime_env = {"working_dir": _tmpdir, "env_vars": _env_vars}',
        "",
        "    if _RAY_JOB_REQUIREMENTS:",
        '        print(f"Including requirements: {_RAY_JOB_REQUIREMENTS}")',
        '        _runtime_env["pip"] = _RAY_JOB_REQUIREMENTS',
        "",
        f'    print(f"Entry point: ./job.pex")',
        f"    print(f\"Resources: CPUs={num_cpus}, GPUs={num_gpus}, Memory={memory}\")",
        "",
        "    job_id = client.submit_job(",
        '        entrypoint="python job.pex",',
        "        runtime_env=_runtime_env,",
        f"        entrypoint_num_cpus={num_cpus},",
        f"        entrypoint_num_gpus={num_gpus},",
        f"        entrypoint_memory={memory},",
        "    )",
        "",
        "    shutil.rmtree(_tmpdir, ignore_errors=True)",
        '    print(f"Submitted job: {job_id}")',
        "    return job_id",
        "",
        "",
        "def main() -> None:",
        '    """Entry point for PEX binary."""',
        "    job_id = submit_job()",
        '    print(f"\\nJob submitted successfully: {job_id}")',
        '    print(f"View status: ray job status {job_id}")',
        '    print(f"View logs: ray job logs {job_id}")',
        "",
        "",
        'if __name__ == "__main__":',
        "    main()",
        "",
    ])

    return "\n".join(lines)
