"""alembic_wrapper.py template for auto-detecting config path."""


def get_alembic_wrapper_template(config_path: str) -> str:
    """Generate alembic_wrapper.py content that auto-detects config path.

    Args:
        config_path: Path to alembic.ini relative to project root

    Returns:
        Python script content for alembic CLI wrapper
    """
    return f'''"""Auto-generated Alembic CLI wrapper with config auto-detection.

Generated by gusi.pants.backend.alembic plugin.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from alembic.config import main as alembic_main


def _get_config_path() -> str:
    """Get absolute path to alembic.ini.

    Uses BUILD_ROOT environment variable set by Pants, with fallback to searching
    for pants.toml if run outside of Pants context.
    """
    # First try BUILD_ROOT env var (set by Pants when running commands)
    buildroot = os.getenv("BUILD_ROOT")

    if buildroot:
        return str(Path(buildroot) / "{config_path}")

    # Fallback: search upwards for pants.toml
    current = Path.cwd().resolve()
    while current != current.parent:
        if (current / "pants.toml").exists():
            return str(current / "{config_path}")
        current = current.parent

    # Last resort: assume current directory is buildroot
    return str(Path.cwd().resolve() / "{config_path}")


def main() -> None:
    """Wrapper for alembic CLI that auto-detects config path."""
    # If -c/--config not already provided, inject it
    if "-c" not in sys.argv and "--config" not in sys.argv:
        # Insert after program name, before subcommand
        sys.argv.insert(1, "-c")
        sys.argv.insert(2, _get_config_path())

    alembic_main()


if __name__ == "__main__":
    main()
'''
