"""commands.py template for Alembic convenience binaries."""


def get_commands_template(config_path: str) -> str:
    """Generate commands.py content with Alembic convenience commands.

    Args:
        config_path: Path to alembic.ini relative to project root

    Returns:
        Python script content with multiple command functions
    """
    return f'''"""Auto-generated Alembic convenience commands.

Generated by gusi.pants.backend.alembic plugin.
"""
import os
import sys
from pathlib import Path
from alembic.config import main as alembic_main


def _get_config_path() -> str:
    """Get absolute path to alembic.ini.

    Uses BUILD_ROOT environment variable set by Pants, with fallback to searching
    for pants.toml if run outside of Pants context.
    """
    # First try BUILD_ROOT env var (set by Pants when running commands)
    buildroot = os.getenv("BUILD_ROOT")

    if buildroot:
        return str(Path(buildroot) / "{config_path}")

    # Fallback: search upwards for pants.toml
    current = Path.cwd().resolve()
    while current != current.parent:
        if (current / "pants.toml").exists():
            return str(current / "{config_path}")
        current = current.parent

    # Last resort: assume current directory is buildroot
    return str(Path.cwd().resolve() / "{config_path}")


def generate():
    """Generate a new migration with autogenerate."""
    sys.argv = ["alembic", "-c", _get_config_path(), "revision", "--autogenerate"] + sys.argv[1:]
    alembic_main()


def upgrade():
    """Upgrade to the latest migration."""
    sys.argv = ["alembic", "-c", _get_config_path(), "upgrade", "head"] + sys.argv[1:]
    alembic_main()


def downgrade():
    """Downgrade one migration."""
    sys.argv = ["alembic", "-c", _get_config_path(), "downgrade", "-1"] + sys.argv[1:]
    alembic_main()
'''
