"""env.py template for Alembic migrations."""

ENV_PY_TEMPLATE = '''"""Alembic environment configuration.

Generated by gusi.pants.backend.alembic plugin.
"""

import os

from alembic import context
from sqlalchemy import engine_from_config, pool

# Import your Base from your service
# TODO: Update this import path to match your project structure
# from your_service.db import Base

config = context.config

# TODO: Set target_metadata to your Base.metadata
# target_metadata = Base.metadata
target_metadata = None


def get_url():
    """Get database URL from environment variable or use default."""
    url = os.getenv("DATABASE_URL", "postgresql://user:password@localhost:5432/db")

    # Convert async driver to sync driver for Alembic
    if url.startswith("postgresql+asyncpg://"):
        url = url.replace("postgresql+asyncpg://", "postgresql://", 1)
    elif url.startswith("psql://"):
        url = url.replace("psql://", "postgresql://", 1)
    elif url.startswith("mysql+aiomysql://"):
        url = url.replace("mysql+aiomysql://", "mysql+pymysql://", 1)

    return url


def run_migrations_offline():
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.
    """
    context.configure(
        url=get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.
    """
    connectable = engine_from_config(
        {"sqlalchemy.url": get_url()},
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''
