"""env.py template for Alembic migrations."""

ENV_PY_TEMPLATE = '''"""Alembic environment configuration.

Generated by gusi.pants.backend.alembic plugin.
"""
from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import context
from sqlalchemy import engine_from_config, pool

if TYPE_CHECKING:
    from sqlalchemy import MetaData

config = context.config


def get_url() -> str:
    """Get database URL for migrations."""
    raise NotImplementedError(
        "\\n"
        "=" * 80 + "\\n"
        "SETUP REQUIRED: Implement get_url() in env.py\\n"
        "=" * 80 + "\\n"
        "You must implement the get_url() function to return your database URL.\\n"
        "\\n"
        "Examples:\\n"
        "\\n"
        "    # From environment variable:\\n"
        "    import os\\n"
        "    return os.getenv(\\"DATABASE_URL\\")\\n"
        "\\n"
        "    # From settings:\\n"
        "    from myapp.settings import settings\\n"
        "    return settings.database_url\\n"
        "\\n"
        "    # From pydantic settings with async driver conversion:\\n"
        "    from myapp.settings import settings\\n"
        "    url = settings.postgres_dsn\\n"
        "    # Convert async driver to sync for Alembic\\n"
        "    if url.startswith(\\"postgresql+asyncpg://\\"):\\n"
        "        url = url.replace(\\"postgresql+asyncpg://\\", \\"postgresql://\\", 1)\\n"
        "    return url\\n"
        "\\n"
        "=" * 80
    )


def get_metadata():
    """Get SQLAlchemy metadata for autogenerate."""
    raise NotImplementedError(
        "\\n"
        "=" * 80 + "\\n"
        "SETUP REQUIRED: Implement get_metadata() in env.py\\n"
        "=" * 80 + "\\n"
        "You must implement the get_metadata() function to return your SQLAlchemy\\n"
        "metadata for autogenerate to work.\\n"
        "\\n"
        "Examples:\\n"
        "\\n"
        "    # Single Base:\\n"
        "    from myapp.models import Base\\n"
        "    return Base.metadata\\n"
        "\\n"
        "    # Multiple models in different modules:\\n"
        "    from myapp.models.user import Base as UserBase\\n"
        "    from myapp.models.product import Base as ProductBase\\n"
        "    # Combine metadata from multiple bases if needed\\n"
        "    return UserBase.metadata\\n"
        "\\n"
        "=" * 80
    )


def run_migrations_offline():
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.
    """
    context.configure(
        url=get_url(),
        target_metadata=get_metadata(),
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.
    """
    connectable = engine_from_config(
        {"sqlalchemy.url": get_url()},
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=get_metadata())

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''
